version: '3.8'

services:
  web:
    build: ./file_upload
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./file_upload/:/usr/src/file_upload/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery:
    build: ./file_upload
    command: celery -A file_upload worker -l info
    volumes:
      - ./file_upload/:/usr/src/file_upload/
    depends_on:
      - redis
      - web

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
